"""empty message

Revision ID: 620578a48060
Revises: 
Create Date: 2025-04-02 12:58:12.094073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '620578a48060'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('player_x_id', sa.String(), nullable=False),
    sa.Column('player_o_id', sa.String(), nullable=False),
    sa.Column('winner', sa.String(), nullable=False),
    sa.Column('game_type', sa.String(), nullable=False),
    sa.Column('board', sa.JSON(), nullable=False),
    sa.Column('moves', sa.JSON(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('game_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_history')
    # ### end Alembic commands ###
