apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: tictactoe
spec:
  ingressClassName: nginx
  rules:
    - host: users.tictactoe.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: users
                port:
                  number: 8000
    - host: game.tictactoe.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: game
                port:
                  number: 8000
    - host: history.tictactoe.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: game-history
                port:
                  number: 8000