apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: tictactoe
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: users.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: users
                port:
                  number: 8000