apiVersion: v1
kind: Secret
metadata:
  name: game-history-service-creds
  namespace: tictactoe
type: Opaque
stringData:
  username: game-history-user
  password: game-history-password
  dbname: game-history