# name: 'users-microservice'
version: '3.9'

services:
  api:
    build:
      context: .
    env_file:
      - ./docker.env
    restart: always
    depends_on:
      - pg-master
      - pg-slave
      - pg-slave2
      - zoo1
      - haproxy
    ports:
      - 8000:8000

  db1:
    image: postgres
    restart: always
    env_file:
      - ./devdb.env
    ports:
      - 5432:5432

      
  adminer:
    image: adminer
    restart: always
    depends_on:
      - pg-master
      - pg-slave
      - pg-slave2
    environment:
      - ADMINER_DESIGN=pepa-linha-dark
    ports:
      - 8080:8080

volumes:
  pg-master_data:
  pg-slave_data:
  pg-slave2_data:
