version: '3.8'
name: users-microservice-dev

services:
  # api:
  #   build:
  #     context: .
  #   env_file:
  #     - ./.env
  #   restart: no
  #   depends_on:
  #     - db1
  #     - mongo1
  #   ports:
  #     - 8000:8000
    
  db1:
    image: postgres
    restart: always
    env_file:
      - ./db.env
    ports:
      - 5432:5432
