version: "3.8"
name: users-microservice

services:
  api:
    build:
      context: .
    env_file:
      - ./.env
    restart: always
    depends_on:
      - postgresql-master
    ports:
      - 8000:8000

  postgresql-master:
    image: docker.io/bitnami/postgresql:17
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    env_file:
      - db_repl.env
    environment:
      - POSTGRESQL_REPLICATION_MODE=master

  postgresql-slave:
    image: docker.io/bitnami/postgresql:17
    ports:
      - '5433:5432'
    depends_on:
      - postgresql-master
    env_file:
      - db_repl.env
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgresql-master
    environment:
      - ADMINER_DESIGN=pepa-linha-dark
    ports:
      - 8080:8080

volumes:
  postgresql_master_data:
    driver: local