version: "3.8"
name: users-microservice

services:
  api:
    build:
      context: .
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db1
    ports:
      - 8000:8000

  db1:
    image: postgres
    volumes:
      - /home/api/postgres/postgres_data_prod:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./db.env

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db1
    environment:
      - ADMINER_DESIGN=pepa-linha-dark
    ports:
      - 8080:8080

volumes:
  postgres_data_prod:
  mongo-data-prod: