# name: 'users-microservice'
version: '3.9'

services:
  api:
    build:
      context: .
    env_file:
      - ./docker.env
    restart: always
    depends_on:
      - pg-master
      - pg-slave
      - pg-slave2
      - zoo1
      - haproxy
    ports:
      - 8000:8000

  haproxy:
    image: haproxy:latest
    ports:
      - 5432:5432
      - 7001:7000
    volumes:
      - ./database/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - zoo1
      - pg-master
      - pg-slave
      - pg-slave2
    command: ["haproxy", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]

  zoo1:
    image: confluentinc/cp-zookeeper:latest
    container_name: zoo
    restart: always
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  pg-master:
    build:
      context: ./database/postgres
    container_name: pg-master
    restart: always
    hostname: pg-master
    env_file:
      - ./db.env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    expose:
      - 5432
      - 8008
    volumes:
      - pg-master_data:/var/lib/postgresql/data
    command: patroni /postgres0.yml

  pg-slave:
    build:
      context: ./database/postgres
    container_name: pg-slave
    restart: always
    hostname: pg-slave
    expose:
      - 5432
      - 8008
    volumes:
      - pg-slave_data:/var/lib/postgresql/data
    env_file:
      - ./db.env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    command: patroni /postgres1.yml

  pg-slave2:
    build:
      context: ./database/postgres
    container_name: pg-slave2
    restart: always
    hostname: pg-slave2
    expose:
      - 5432
      - 8008
    volumes:
      - pg-slave2_data:/var/lib/postgresql/data
    env_file:
      - ./db.env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    command: patroni /postgres2.yml

  adminer:
    image: adminer
    restart: always
    depends_on:
      - pg-master
      - pg-slave
      - pg-slave2
    environment:
      - ADMINER_DESIGN=pepa-linha-dark
    ports:
      - 8080:8080

volumes:
  pg-master_data:
  pg-slave_data:
  pg-slave2_data:
