name: users-microservice-repl

services:
  postgresql-master:
    image: docker.io/bitnami/postgresql:17
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    env_file:
      - db_repl.env
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
  postgresql-slave:
    image: docker.io/bitnami/postgresql:17
    ports:
      - '5433:5432'
    depends_on:
      - postgresql-master
    env_file:
      - db_repl.env
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave


volumes:
  postgresql_master_data:
    driver: local